version: "3.8"
services:
    clinic_app:
        container_name: clinic_app
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        expose:
            - 9000
        volumes:
            - .:/usr/src/app
            - ./public:/usr/src/app/public
        depends_on:
            - clinic_db
        networks:
            - app_network

    clinic_nginx:
        container_name: clinic_nginx
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
        volumes:
            - ./public:/usr/src/app/public
        ports:
            - 8000:80
        depends_on:
            - clinic_app
        environment:
            NGINX_FPM_HOST: clinic_app
            NGINX_ROOT: /usr/src/app/public
        networks:
            - app_network

    clinic_db:
        container_name: clinic_db
        image: mysql:8.0.20
        restart: always
        volumes:
            - ./storage/db-data:/var/lib/mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: clinic
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: root
            MYSQL_PASSWORD:
        networks:
            - app_network

    clinic_redis:
        container_name: clinic_redis
        image: redis:latest
        ports:
            - 6379:6379
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
